/**
 * Seed Service Packages Script
 * Seeds service packages into the database
 */

const servicePackages = [
  // Article Writing Packages
  {
    serviceId: "article-writing",
    name: "Starter Package",
    price: 150,
    originalPrice: 200,
    articles: "3 Articles",
    features: [
      "500-800 words per article",
      "Basic SEO optimization",
      "1 revision per article",
      "5-7 day delivery",
      "General topics",
    ],
    popular: false,
    description: "Perfect for small businesses starting their content marketing journey",
    status: "active",
    order: 1,
  },
  {
    serviceId: "article-writing",
    name: "Professional Package",
    price: 450,
    originalPrice: 600,
    articles: "10 Articles",
    features: [
      "800-1200 words per article",
      "Advanced SEO optimization",
      "2 revisions per article",
      "3-5 day delivery",
      "Industry-specific content",
      "Meta descriptions included",
    ],
    popular: true,
    description: "Ideal for growing businesses looking to scale their content strategy",
    status: "active",
    order: 2,
  },
  {
    serviceId: "article-writing",
    name: "Enterprise Package",
    price: 1200,
    originalPrice: 1600,
    articles: "30 Articles",
    features: [
      "1000-1500 words per article",
      "Premium SEO optimization",
      "Unlimited revisions",
      "24-48 hour delivery",
      "Expert industry writers",
      "Content strategy consultation",
      "Priority support",
    ],
    popular: false,
    description: "Comprehensive solution for established businesses with high content needs",
    status: "active",
    order: 3,
  },
  // Link Insertions Packages
  {
    serviceId: "link-insertions",
    name: "Basic Link Package",
    price: 485,
    originalPrice: 650,
    articles: "5 Link Insertions",
    features: [
      "DA 40-60 websites",
      "Contextual placements",
      "Permanent links",
      "Basic reporting",
      "30-day delivery",
    ],
    popular: false,
    description: "Great starting point for building your backlink profile",
    status: "active",
    order: 1,
  },
  {
    serviceId: "link-insertions",
    name: "Premium Link Package",
    price: 1455,
    originalPrice: 1940,
    articles: "15 Link Insertions",
    features: [
      "DA 60-80 websites",
      "Strategic anchor text",
      "Detailed link reports",
      "20-day delivery",
      "Niche-relevant sites",
      "Link monitoring included",
    ],
    popular: true,
    description: "Most popular choice for serious link building campaigns",
    status: "active",
    order: 2,
  },
  {
    serviceId: "link-insertions",
    name: "Authority Link Package",
    price: 3880,
    originalPrice: 5170,
    articles: "40 Link Insertions",
    features: [
      "DA 80+ premium websites",
      "Custom anchor strategies",
      "Comprehensive reporting",
      "15-day delivery",
      "Industry-specific targeting",
      "Dedicated account manager",
      "6-month link monitoring",
    ],
    popular: false,
    description: "Premium solution for maximum authority building",
    status: "active",
    order: 3,
  },
  // HOTH Digital PR Packages
  {
    serviceId: "hoth-digital-pr",
    name: "Startup PR Package",
    price: 497,
    originalPrice: 650,
    articles: "1 Month Campaign",
    features: [
      "5 media outreach attempts",
      "Press release writing",
      "Basic media list",
      "Email campaign management",
      "Monthly reporting",
    ],
    popular: false,
    description: "Perfect introduction to digital PR for new businesses",
    status: "active",
    order: 1,
  },
  {
    serviceId: "hoth-digital-pr",
    name: "Growth PR Package",
    price: 1245,
    originalPrice: 1650,
    articles: "3 Month Campaign",
    features: [
      "15 media outreach attempts",
      "2 press releases included",
      "Targeted media lists",
      "Follow-up campaigns",
      "Social media amplification",
      "Bi-weekly reporting",
    ],
    popular: true,
    description: "Comprehensive PR strategy for growing businesses",
    status: "active",
    order: 2,
  },
  {
    serviceId: "hoth-digital-pr",
    name: "Enterprise PR Package",
    price: 2985,
    originalPrice: 3980,
    articles: "6 Month Campaign",
    features: [
      "Unlimited outreach attempts",
      "4 press releases included",
      "Premium media database",
      "Crisis management support",
      "Influencer outreach",
      "Dedicated PR manager",
      "Weekly strategy calls",
    ],
    popular: false,
    description: "Full-service PR solution for established enterprises",
    status: "active",
    order: 3,
  },
  // Content Syndication Packages
  {
    serviceId: "content-syndication",
    name: "Basic Syndication",
    price: 197,
    originalPrice: 260,
    articles: "5 Platform Distribution",
    features: [
      "5 syndication platforms",
      "Basic content optimization",
      "Standard distribution",
      "Performance tracking",
      "7-day campaign",
    ],
    popular: false,
    description: "Simple content amplification for small businesses",
    status: "active",
    order: 1,
  },
  {
    serviceId: "content-syndication",
    name: "Premium Syndication",
    price: 485,
    originalPrice: 650,
    articles: "15 Platform Distribution",
    features: [
      "15 premium platforms",
      "Advanced optimization",
      "Priority distribution",
      "Social media boost",
      "Detailed analytics",
      "5-day campaign",
    ],
    popular: true,
    description: "Enhanced reach across multiple premium platforms",
    status: "active",
    order: 2,
  },
  {
    serviceId: "content-syndication",
    name: "Enterprise Syndication",
    price: 1165,
    originalPrice: 1550,
    articles: "30+ Platform Distribution",
    features: [
      "30+ premium platforms",
      "Custom content adaptation",
      "Immediate distribution",
      "Multi-channel promotion",
      "Real-time analytics",
      "Dedicated campaign manager",
      "3-day campaign",
    ],
    popular: false,
    description: "Maximum exposure across all available channels",
    status: "active",
    order: 3,
  },
  // Press Releases Packages
  {
    serviceId: "press-releases",
    name: "Standard Release",
    price: 297,
    originalPrice: 400,
    articles: "1 Press Release",
    features: [
      "Professional PR writing",
      "50+ news outlets",
      "Basic distribution",
      "SEO optimization",
      "Distribution report",
    ],
    popular: false,
    description: "Professional press release for announcements",
    status: "active",
    order: 1,
  },
  {
    serviceId: "press-releases",
    name: "Premium Release",
    price: 745,
    originalPrice: 1000,
    articles: "3 Press Releases",
    features: [
      "Expert PR copywriting",
      "200+ premium outlets",
      "Targeted distribution",
      "Advanced SEO optimization",
      "Social media amplification",
      "Detailed analytics",
    ],
    popular: true,
    description: "Comprehensive press release campaign",
    status: "active",
    order: 2,
  },
  {
    serviceId: "press-releases",
    name: "Enterprise Release",
    price: 1785,
    originalPrice: 2400,
    articles: "8 Press Releases",
    features: [
      "C-suite level writing",
      "500+ major outlets",
      "Priority distribution",
      "Multi-format releases",
      "Influencer outreach",
      "Crisis management support",
      "Dedicated PR specialist",
    ],
    popular: false,
    description: "Enterprise-level press release strategy",
    status: "active",
    order: 3,
  },
];

// Seed using curl commands
console.log("Copy and run these commands to seed service packages:\n");

servicePackages.forEach((pkg) => {
  const cmd = `curl -X POST http://localhost:5000/api/v1/service-packages -H "Content-Type: application/json" -d '${JSON.stringify(pkg).replace(/'/g, "'\\''")}' && echo ""`;
  console.log(cmd);
  console.log("");
});

